name = input()
cost = int(input())
weight = int(input())
count = int(input())

print("Чек")
print(f"{name} - {weight}кг - {cost}руб/кг")
print(f"Итого: {weight * cost}руб")
print(f"Внесено: {count}руб")
print(f"Сдача: {count - weight * cost}руб")